# ==========================
# WebsiteCaptcha Plugin Configuration
# ==========================
# This configuration ensures players complete a CAPTCHA on a designated website
# before accessing the server. Players are temporarily placed in a virtual
# lobby and prompted to verify. Once verified, they can proceed to the main server.

# --------------------------
# Messages
# --------------------------
# Messages displayed to players during the verification process. Use '&' for color codes.
# Examples: &a (green), &c (red), &e (yellow), &b (blue). Use '\n' for line breaks.
messages:
  already_verified: "&aWelcome back! You are still verified."
  verification_prompt: "&eWelcome! Please verify yourself by clicking this link: "
  verification_link_text: "&b[Verify Here]"
  verification_success: "&aThank you for verifying! Enjoy the server."
  verification_failed: "&cVerification failed. Please try again later."
  verification_timeout_kick: "&cVerification failed. Please try again later.\n&4You appear to be a bot!"
  no_command_permission: "&cYou cannot use commands until you are verified."
  no_chat_permission: "&cYou cannot chat until you are verified."
  inventory_hidden: "&cYour inventory is hidden until you verify."
  inventory_restored: "&aYour inventory has been restored after verification."
  block_breaking: "&cYou cannot break blocks while unverified!"
  block_placing: "&cYou cannot place blocks while unverified!"
  item_dropping: "&cYou cannot drop items while unverified!"
  item_picking_up: "&cYou cannot pick up items while unverified!"
  inventory_clicking: "&cYou cannot interact with the inventory while unverified!"
  attack: "&cYou cannot attack while unverified!"
  receive_damage: "&cYou cannot receive damage while unverified!"
  reload_success: "§aPlugin configuration reloaded successfully!"
  no_permission: "§cYou do not have permission to use this command."
  clear_success: "§aVerification cleared for player: %player%"
  set_success: "§aVerification successfully set for player: %player%"
  player_not_found: "§cPlayer not found."

# --------------------------
# Behavior Options
# --------------------------
# Controls for player restrictions during the verification process.
options:
  # Apply a blindness effect to unverified players. If disabled, ensure any existing
  # blindness effects are removed to avoid issues.
  apply_blindness: true

  # Game mode for unverified players in Limbo (SURVIVAL, SPECTATOR, ADVENTURE, CREATIVE)
  game_mode: ADVENTURE  # Default: ADVENTURE

  # Time (in seconds) players have to verify before being kicked
  verification_timeout: 60

  # Duration (in milliseconds) a verification session remains valid before requiring re-verification
  verification_grace_period: 86400000  # 24 hours

  # Whether to send a title to unverified players in Limbo (true/false)
  SendTitle: false
  # Title text to display (supports color codes with &)
  title: "&aWelcome To Server"
  # Subtitle text to display (supports color codes with &)
  subtitle: "&aThanks for using my plugin"

  # Whether to send an action bar message to unverified players in Limbo (true/false)
  SendActionBar: false
  # Action bar text to display (supports color codes with &)
  actionBar: "&ePlease verify to join!"

  # Whether to send a chat message to unverified players in Limbo (true/false)
  SendChatMessage: false
  # Chat message text to display (supports color codes with &)
  chatMessage: "&eClick the link to verify!"

  # Prevent unverified players from moving. If false, they can move freely.
  prevent_unverified_player_movement: true

  # Prevent unverified players from using any commands.
  prevent_command_use: true

  # Prevent unverified players from chatting.
  prevent_chat: true

  # Hide unverified players' inventory. Restores inventory upon verification.
  hide_inventory: true

  # Restrictions on unverified players' block and item interactions.
  blockBreaking: false        # False = Block breaking is blocked
  blockPlacing: false         # False = Block placing is blocked
  itemDrop: false             # False = Item dropping is blocked
  itemPickup: false           # False = Item pickup is blocked
  inventoryClick: false       # False = Inventory clicking is blocked

  # Restrictions on damage-related actions for unverified players.
  damage:
    attack: false             # False = Players cannot attack others
    receive: false            # False = Players cannot receive damage

# --------------------------
# Web Server Configuration
# --------------------------
# Configuration for the verification web server. Ensure the port is open if hosting externally.
Web:
  # Host Address:
  # 1. This option must be filled with either:
  #    - The machine's IP address (e.g., "192.168.1.100") if hosting locally.
  #    - A domain name (e.g., "verify.yourserver.com") if hosting externally.
  # 2. Why it's important:
  #    - The host value is used to generate the verification link sent to players upon joining.
  #    - If left empty, the default value will be "localhost," which resolves to the machine's internal loopback IP (127.0.0.1).
  #    - Links with "localhost" will only work for the same machine where the server is running. Other players won't be able to access the verification website.
  # 3. Local Hosting:
  #    - Use your machine's local IP (e.g., "192.168.x.x") to allow players on the same network to access the verification link.
  #    - Example: "http://192.168.1.100:8080".
  # 4. External Hosting:
  #    - Use a domain name (e.g., "verify.yourserver.com") and configure DNS to point to your server.
  #    - Ensure the specified port (see below) is open and accessible through your firewall and router.
  # 5. If this value is not configured:
  #    - Players will receive a verification link with "localhost," which will not work for anyone other than the server's host machine.
  host: ""
  # Port Configuration:
  # 1. Specify the port number for the web server:
  #    - Default: 8080
  #    - You can use any available port (e.g., 9090, 2020, etc.).
  # 2. Why this is important:
  #    - The port must be open and accessible for the verification website to function.
  #    - Players will receive a link in the format: "http://<host>:<port>". Ensure the port is correct and accessible.
  # 3. Hosting Notes:
  #    - If you're hosting the server locally, ensure the port is not used by other services.
  #    - For external hosting, ensure the port is open in your firewall and router. Use command /webcaptcha portcheck <ip> <port> to verify that the port is open.
  # 4. Examples:
  #    - Local setup: port: 8080 (access via http://192.168.x.x:8080).
  #    - External setup: port: 9090 (access via http://verify.yourserver.com:9090).
  port: 8080

# --------------------------
# reCAPTCHA Configuration
# --------------------------
# Settings for Google reCAPTCHA (v2) integration on the verification website.
recaptcha:
  # Site key for identifying your website to the reCAPTCHA service.
  # Obtain this key from the Google reCAPTCHA admin console.
  site_key: ""

  # Secret key for secure server-side communication with the reCAPTCHA service.
  # Keep this key confidential.
  secret_key: ""
