name: WebsiteCaptcha
version: '1.0-SNAPSHOT'
main: me.salman.websiteCaptcha.Main
api-version: '1.20'
depend: [ ProtocolLib ]
commands:
  webcaptcha:
    description: Main command for the WebsiteCaptcha plugin
    usage: /webcaptcha
    permission: webcaptcha.command
    permission-message: You do not have permission to use this command.