name: WebsiteCaptcha
version: '1.0-SNAPSHOT'
main: me.salman.websiteCaptcha.Main
api-version: '1.20'
depend: [ ProtocolLib ]
libraries:
  - org.eclipse.jetty:jetty-server:11.0.15
  - org.eclipse.jetty:jetty-servlet:11.0.15
  - org.eclipse.jetty:jetty-http:11.0.15
  - org.eclipse.jetty:jetty-util:11.0.15
  - org.xerial:sqlite-jdbc:3.49.1.0
commands:
  webcaptcha:
    description: Main command for the WebsiteCaptcha plugin
    usage: /webcaptcha
    permission: webcaptcha.command
    permission-message: You do not have permission to use this command.